# Generated by Django 3.1.7 on 2021-03-16 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.IntegerField()),
                ('anio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('estado', models.IntegerField(choices=[(1, 'Entregado'), (2, 'Aprobado'), (3, 'Rechazado')], default=1)),
                ('calificacion', models.IntegerField(default=0)),
                ('hashtag', models.ManyToManyField(to='repositorio.Hashtag')),
                ('idGrupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='repositorio.grupo')),
                ('idMateria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='repositorio.materia')),
                ('idPersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.persona')),
                ('idSemestre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='repositorio.semestre')),
                ('idTipoTrabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='repositorio.tipotrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='trabajos')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.fase')),
                ('idTrabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.trabajo')),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTrabajo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='repositorio.trabajo')),
                ('idpersona', models.ManyToManyField(to='users.Persona')),
            ],
        ),
    ]
