# Generated by Django 3.1.7 on 2021-03-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='file',
            field=models.FileField(upload_to='trabajos'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Entregado'), (2, 'Aprobado'), (3, 'Rechazado')], default=1),
        ),
    ]
